global:
  release_version: release-7.0.0
  # Provide your domain name
  # Example: sunbird.com
  domain: ""
  # The merge domain is optional and is required only if user merge workflow is required.
  # For most audience, this workflow is not required. If you need this workflow, then
  # set the value of merge_domain_status to "true" and provide a subdomain / another domain
  merge_domain_status: "false"
  merge_domain: ""
  proxy_private_key: |
